# Generated by Django 4.0.5 on 2022-06-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_team_chat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_team_id', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('details', models.JSONField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.team')),
            ],
        ),
    ]
