# Generated by Django 4.0.5 on 2022-08-15 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('internal_value', models.CharField(max_length=100)),
                ('attribute_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributebase')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_bases',
            field=models.ManyToManyField(to='products.attributebase'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(to='products.attribute'),
        ),
    ]
