# Generated by Django 4.0.5 on 2023-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productattributestock_alter_product_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('used', models.IntegerField(default=0)),
                ('usage_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_attributes', models.ManyToManyField(to='products.attributebase')),
                ('assigned_products', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
